package ProjectEuler;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * Copyright © 2021 ProjectEuler.net
 * Source: https://projecteuler.net/problem=2
 */

class Problem2 {
    static int solveProblem2() {
        int currentTermsValue;
        int previousTermsValue = 1;
        int secondToPreviousTermsValue = 0;
        int sumOfEvenValuedTerms = 0;
        do {
            currentTermsValue = secondToPreviousTermsValue + previousTermsValue;
            secondToPreviousTermsValue = previousTermsValue;
            previousTermsValue = currentTermsValue;
            if (currentTermsValue % 2 == 0) {
                sumOfEvenValuedTerms += currentTermsValue;
            }
        } while (currentTermsValue < 4000000);
        return sumOfEvenValuedTerms;
    }
}
