package ProjectEuler;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * Source: https://projecteuler.net/problem=2
 * Copyright © 2021 ProjectEuler.net
 */

public class Problem2 {
    static int solveProblem2() {
        int previousTermsValue = 0;
        int termsValue = 1;
        int valueOfCurrentTerm;
        int sumOfEvenValuedTerms = 0;
        do {
            valueOfCurrentTerm = previousTermsValue + termsValue;
            previousTermsValue = termsValue;
            termsValue = valueOfCurrentTerm;
            if (valueOfCurrentTerm % 2 == 0) {
                sumOfEvenValuedTerms += valueOfCurrentTerm;
            }
        } while (valueOfCurrentTerm < 4000000);
        return sumOfEvenValuedTerms;
    }
}
